In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
from matplotlib import pyplot as plt

In [24]:
frame_statistic_functions = [
    ["Head", lambda frame: frame.head()],
    ["Data Description", lambda frame: frame.describe()],
    ["Number of NaN values", lambda frame: frame.isna().sum()]
]

column_statistic_functions = [
    ["value counts", lambda frame, column: frame[column].value_counts()]
]

In [31]:
client_data = pd.read_csv("./data_science_exam_bluevine_file.csv")

In [42]:

for func in frame_statistic_functions:
    print("\r\n%s:\r\n%s" % (func[0],func[1](client_data)))

for func in column_statistic_functions:
    print("\r\n%s:\r\n%s" % (func[0],func[1](client_data,'period')))

client_data.describe()

Head:
   client_id     pit            period segment  recent_successful_repayments  \
0      37544  7/2/16  first_funded+120     old                   7042.072861
1      42193  7/2/16  first_funded+120     old                           NaN
2      23697  7/2/16  first_funded+120     old                           NaN
3      24142  7/2/16  first_funded+120     old                           NaN
4      23757  7/2/16  first_funded+120     old                           NaN

   Current_model_probability  available_credit       balance  \
0                   0.688518        541.896948   9494.157563
1                   0.651311       1234.448117   8787.884771
2                   0.467099     -10415.873360  20430.078210
3                   0.303301               NaN   6718.722185
4                   0.130349      24978.660420    969.848128

   sum_failed_repayments   max_failed_repayments  credit_score  \
0              478.740572             138.126594         623.0
1                     NaN                    NaN         617.0
2                     NaN                    NaN         684.0
3                     NaN                    NaN         631.0
4                     NaN                    NaN         712.0

   external score  credit_inquiries_count  credit_open_balance  \
0           900.5                     6.0              41608.0
1           891.5                     3.0              55912.0
2           992.0                    27.0              61338.0
3           912.5                    10.0             321223.0
4          1034.0                     5.0             470053.0

             years_on_file  max_successful_repayments  missing_report  \
0    between 5 and 6 years                        NaN               0
1                      NaN                        NaN               0
2  between 0.5 and 1 years                        NaN               0
3  between 12 and 14 years                        NaN               0
4  between 2 and 2.5 years                        NaN               0

   client_industry_unknown tag_in_six_months
0                        0               bad
1                        0               bad
2                        0               bad
3                        0              good
4                        0              good

Data Description:
          client_id  recent_successful_repayments  Current_model_probability  \
count   6604.000000                   6562.000000                6604.000000
mean   14826.917929                  11524.982182                   0.247171
std     9820.563677                  15031.182411                   0.189656
min       13.000000                   -153.457514                   0.000160
25%     7014.000000                   3643.552511                   0.103458
50%    13586.000000                   8105.940537                   0.212537
75%    20849.000000                  14514.614920                   0.350638
max    46338.000000                 485126.766200                   0.964439

       available_credit        balance  sum_failed_repayments   \
count       6484.000000    6502.000000             6368.000000
mean       10483.777215   11225.369333              383.572521
std        12607.400936   12080.434121             1547.943383
min       -34469.619210   -3440.848960                0.000000
25%         2193.595006    2319.123436                0.000000
50%         6472.896701    8135.318744                0.000000
75%        15037.717625   16607.846940                0.000000
max       150020.533000  140135.168200            28344.604620

       max_failed_repayments  credit_score  external score  \
count            6368.000000   5809.000000     6604.000000
mean              131.812131    666.500603      845.399303
std               662.044870    231.513889      460.358896
min                 0.000000 -10003.000000   -15038.500000
25%                 0.000000    636.000000      897.500000
50%                 0.000000    665.000000      951.500000
75%                 0.000000    697.000000     1004.000000
max             24224.772610   9002.000000    13469.000000

       credit_inquiries_count  credit_open_balance  max_successful_repayments  \
count             5782.000000         5.753000e+03                3480.000000
mean                10.192321         2.351489e+05                  13.040408
std                 11.581112         2.764884e+05                   9.516599
min                 -2.000000         0.000000e+00                  -7.000000
25%                  3.000000         4.615700e+04                   2.000000
50%                  7.000000         1.422930e+05                  15.000000
75%                 13.000000         3.376720e+05                  21.000000
max                142.000000         3.683657e+06                  33.000000

       missing_report  client_industry_unknown
count     6604.000000              6604.000000
mean         0.000303                 0.024379
std          0.017401                 0.154235
min          0.000000                 0.000000
25%          0.000000                 0.000000
50%          0.000000                 0.000000
75%          0.000000                 0.000000
max          1.000000                 1.000000

Number of NaN values:
client_id                          0
pit                                0
period                             0
segment                            0
recent_successful_repayments      42
Current_model_probability          0
available_credit                 120
balance                          102
sum_failed_repayments            236
max_failed_repayments            236
credit_score                     795
external score                     0
credit_inquiries_count           822
credit_open_balance              851
years_on_file                   1198
max_successful_repayments       3124
missing_report                     0
client_industry_unknown            0
tag_in_six_months                  0
dtype: int64

value counts:
first_funded+180    3342
first_funded+120    3262
Name: period, dtype: int64

,client_id,recent_successful_repayments,Current_model_probability,available_credit,balance,sum_failed_repayments,max_failed_repayments,credit_score,external score,credit_inquiries_count,credit_open_balance,max_successful_repayments,missing_report,client_industry_unknown
count,6604.000000,6562.000000,6604.000000,6484.000000,6502.000000,6368.000000,6368.000000,5809.000000,6604.000000,5782.000000,5.753000e+03,3480.000000,6604.000000,6604.000000
mean,14826.917929,11524.982182,0.247171,10483.777215,11225.369333,383.572521,131.812131,666.500603,845.399303,10.192321,2.351489e+05,13.040408,0.000303,0.024379
std,9820.563677,15031.182411,0.189656,12607.400936,12080.434121,1547.943383,662.044870,231.513889,460.358896,11.581112,2.764884e+05,9.516599,0.017401,0.154235
min,13.000000,-153.457514,0.000160,-34469.619210,-3440.848960,0.000000,0.000000,-10003.000000,-15038.500000,-2.000000,0.000000e+00,-7.000000,0.000000,0.000000
25%,7014.000000,3643.552511,0.103458,2193.595006,2319.123436,0.000000,0.000000,636.000000,897.500000,3.000000,4.615700e+04,2.000000,0.000000,0.000000
50%,13586.000000,8105.940537,0.212537,6472.896701,8135.318744,0.000000,0.000000,665.000000,951.500000,7.000000,1.422930e+05,15.000000,0.000000,0.000000
75%,20849.000000,14514.614920,0.350638,15037.717625,16607.846940,0.000000,0.000000,697.000000,1004.000000,13.000000,3.376720e+05,21.000000,0.000000,0.000000
max,46338.000000,485126.766200,0.964439,150020.533000,140135.168200,28344.604620,24224.772610,9002.000000,13469.000000,142.000000,3.683657e+06,33.000000,1.000000,1.000000

In [18]:
client_data_plus_120 = client_data[client_data["period"] == "first_funded+120"]
client_data_plus_180 = client_data[client_data["period"] == "first_funded+180"]
print("Original size: %d, funded+120 size=%d, funded+180 size=%d" % \
      (client_data.shape[0],client_data_plus_120.shape[0],client_data_plus_180.shape[0]))

Original size: 6604, funded+120 size=3262, funded+180 size=3342

In [44]:
client_data_plus_180.nunique(dropna=True)

client_id                       3264
pit                              316
period                             1
segment                            2
recent_successful_repayments    3340
Current_model_probability       3032
available_credit                3302
balance                         3312
sum_failed_repayments            775
max_failed_repayments            775
credit_score                     282
external score                   283
credit_inquiries_count            78
credit_open_balance             2876
years_on_file                     18
max_successful_repayments         40
missing_report                     2
client_industry_unknown            2
tag_in_six_months                  2
dtype: int64

In [23]:
client_data['period'].value_counts()

first_funded+180    3342
first_funded+120    3262
Name: period, dtype: int64

In [46]:
print(client_data['period'].unique())

['first_funded+120' 'first_funded+180']